### ISSUE TITLE
Count not displaying (following instructions in docs)

### ISSUE THREAD

**Issue by molson504x** [chilts/pluralise#1]
According to the documentation, I should be able to do `pluralize(count, '% object', null, 'no objects')` and have it display the number of objects (ex: '5 objects' when count = 5).  What I'm actually seeing displayed is '% objects'.  Do I have to change my pluralize call to be `pluralize.withCount()` instead of just the base `pluralize` call?

If so, can you please update your documentation?

Thanks!

**Comment by chilts** [comment]
Ah, sorry about that. The docs are now updated.

BTW, it's `pluralise`, not `pluralize`. :)

Released to npm as v1.0.0. Thanks.
